//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyLittleWorkerAnt.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class stgWarehouseSync
    {
        public string PatientPathwayIdentifier { get; set; }
        public string Standard { get; set; }
        public string Compliance { get; set; }
        public string SuspectedCancer { get; set; }
        public string SourceofreferralForOutpatients { get; set; }
        public string FirstSeenProvider { get; set; }
        public string ReferringGPCCG { get; set; }
        public Nullable<System.DateTime> DateFirstSeen { get; set; }
        public string PrimaryDiagnosis { get; set; }
        public string FirstTreatmentProvider { get; set; }
        public string TreatmentModality { get; set; }
        public string TreatmentEventType { get; set; }
        public Nullable<System.DateTime> DateFirstTreatment { get; set; }
        public Nullable<System.DateTime> TreatmentStartDateCancer { get; set; }
        public Nullable<int> NumberOfDaysReferralToFirstSeen { get; set; }
        public Nullable<int> NumberOfDaysReferralToFirstTreatment { get; set; }
        public Nullable<int> NumberOfDaysDecisionToTreatOrSubsequentTreatment { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<System.DateTime> AuditTimeStamp { get; set; }
        public Nullable<int> LoadID { get; set; }
        public Nullable<int> CancerCareSetting { get; set; }
    }
}
