//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CwtStage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StgODS_CCG
    {
        public int DSS_KEY { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string NATIONAL_GROUPING { get; set; }
        public string HIGH_LEVEL_HEALTH_GEOGRAPHY { get; set; }
        public string ADDRESS_LINE_1 { get; set; }
        public string ADDRESS_LINE_2 { get; set; }
        public string ADDRESS_LINE_3 { get; set; }
        public string ADDRESS_LINE_4 { get; set; }
        public string ADDRESS_LINE_5 { get; set; }
        public string POSTCODE { get; set; }
        public Nullable<System.DateTime> OPEN_DATE { get; set; }
        public Nullable<System.DateTime> CLOSE_DATE { get; set; }
        public string ORGANISATION_SUB_TYPE_CODE { get; set; }
        public Nullable<System.DateTime> DSS_RECORD_START_DATE { get; set; }
        public Nullable<System.DateTime> DSS_RECORD_END_DATE { get; set; }
        public Nullable<System.DateTime> DSS_SYSTEM_CREATED_DATE { get; set; }
        public Nullable<System.DateTime> DSS_SYSTEM_UPDATED_DATE { get; set; }
    }
}
