//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CwtStage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class stgWarehouseSync
    {
        public string PatientPathwayIdentifier { get; set; }
        public string Standard { get; set; }
        public string IsBreach { get; set; }
        public string SuspectedCancer { get; set; }
        public string SourceofreferralForOutpatients { get; set; }
        public string SiteCodeProviderFirstSeen { get; set; }
        public string GpPractiseCodeToCcg { get; set; }
        public Nullable<System.DateTime> DateFirstSeen { get; set; }
        public string PrimaryDiagnosisIcd10 { get; set; }
        public string SiteCodeTreatmentStartDateCancer { get; set; }
        public string CancerTreatmentModality { get; set; }
        public string CancerTreatmentEventType { get; set; }
        public Nullable<System.DateTime> CancerTreatmentPeriodStartDate { get; set; }
        public Nullable<System.DateTime> TreatmentStartDateCancer { get; set; }
        public Nullable<int> DaysBetweenConsultantUpgradeAndTreatmentStart { get; set; }
        public Nullable<int> DaysBetweenReferralAndFirstSeen { get; set; }
        public Nullable<int> DaysBetweenReferralAndTreatmentStart { get; set; }
        public Nullable<int> DaysBetweenTreatmentPeriodStartAndTreatmentStart { get; set; }
        public Nullable<int> Version_ID { get; set; }
        public Nullable<System.DateTime> System_Effective_Start_DateTime { get; set; }
        public Nullable<System.DateTime> System_Effective_End_DateTime { get; set; }
        public Nullable<int> LoadID { get; set; }
        public Nullable<int> CancerCareSetting { get; set; }
    }
}
